services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}'
      - 'MYSQL_USER=${DB_USER}'
    ports:
      - "${DB_PORT}:3306"
